### ISSUE TITLE
coveralls einführen

### ISSUE THREAD

**Issue by jangalinski** [needle4j/needle4j#15]
https://coveralls.io/

**Comment by jangalinski** [comment]
No more free usage, wont pay $5/month ...

**Comment by kaiwinter** [comment]
For open source [it is free](https://coveralls.io/pricing):
> Coveralls is and will always be free for open source projects.

**Comment by jangalinski** [comment]
I am not able to select the open source plan ... can you?

**Comment by kaiwinter** [comment]
You don´t need to select the open source plan, it´s the default. Just [add the github project](https://coveralls.io/repos/new) and configure your project to call the `coveralls:report` target.
