### ISSUE TITLE
[Question] ability to specify the persistence.xml file

### ISSUE THREAD

**Issue by jeromevdl** [needle4j/needle4j#17]
Is there any way to specify the path to the persistence.xml in order to test over different configurations ? I guess no, but it could be interesting to test various configuration...

**Comment by jangalinski** [comment]
I just checked and I do not see any option to do so. It is however possible to configure the path to the hibernate-cfg file. Maybe that is an option?
I myself worked with needle and jpa in a way that I have a production persistence.xml in src/main/resources and a one for testing in src/test. Needle uses the test configuration and I am good to go. Could you explain why you would need more than this prod/test stage switch on jpa level?

**Comment by jeromevdl** [comment]
Indeed, i wanted to validate my mapping (on a legacy database) during test phase instead of deployment phase (hibernate property hibernate.hbm2ddl.auto=validate). With needle you need to set it to create. 

Finally, I've created a test with only hibernate (without JPA / needle...) to check that.

**Comment by mdahm** [comment]
This issue has been fixed in needle4k:

https://github.com/needle4k/needle4k

Just use a different persistence unit name
