### ISSUE TITLE
mock.provider dynamisch setzen

### ISSUE THREAD

**Issue by abendt** [needle4j/needle4j#18]
aktuell ist es notwendig mock.provider in needle.properties explizit zu setzen.
besser wäre es einfach den classpath zu untersuchen ob Mockito bzw. EasyMock vorhanden ist und den default entsprechend zu setzen. Damit wäre die Konfiguration einfacher

**Comment by jangalinski** [comment]
This really is an interesting idea. Care to provide a pull request?

**Comment by jangalinski** [comment]
thanks, and sorry it took so long. Will have a 2.4 release soon
