### ISSUE TITLE
Add configuration option for @ObjectUnderTest to execute @PostConstruct as default

### ISSUE THREAD

**Issue by McPringle** [needle4j/needle4j#21]
In all my tests I need to execute the post construct method for my object under test, e.g.:

```
@ObjectUnderTest(postConstruct = true)
private MyObject myObject;
```

It would be great to be able to specify this as a default in `needle.properties` so I can't forget to set it. I'll look forward to implement this and provide a pull request.

**Comment by jangalinski** [comment]
Hi Marcus,

great idea ... when I introduced the postConstruct run, we made it optional for backward compatibility ... but your idea to switch it via properties is an even better solution. Would definitely be open for a PR.

Thanks
Jan

**Comment by McPringle** [comment]
Hi Jan

I'll attend the [Hackergarten](http://hackergarten.net/) events in [Basel](https://www.meetup.com/Hackergarten-Basel/events/234993108/) and [Lucerne](https://www.meetup.com/Hackergarten-Luzern/events/hjxkglyvqbcb/) and will suggest this task to be implemented there.

Enjoy the weekend
Marcus

**Comment by McPringle** [comment]
There is a new setting for the `needle.properties` configuration file:

```
postconstruct.executestrategy = always | never | default
```

If the configuration option is not specified or has an invalid value it defaults to `default` and works like before. If you specify `always`, the post construct method will be executed always regardless of the post construct parameter value and `never` does not execute it at all. More or less self-explanatory, we hope… :-)

**Comment by McPringle** [comment]
We had a lot of fun coding on Needle4J at the Hackergarten Basel this November: https://www.meetup.com/Hackergarten-Basel/photos/27426669/#456108286

**Comment by jangalinski** [comment]
Thanks! I will have to check the sonartype credentials for releasing, please have some patience, might have to wait til the weekend

**Comment by McPringle** [comment]
Thank you very much for merging our PR! I have some experience in using SonarQube for open source projects. You can contact me if you need help solving the problem.

**Comment by jangalinski** [comment]
Hi Marcus, sorry, got a lot of other stuff on my mind right now. I want to come back to your offer to help out ... I made you member of the needle4j crew and will send you the sonatype credentials required for mvn central releases, ok?   Jan

**Comment by McPringle** [comment]
Hi Jan, sounds good, looks like I'll have time to investigate this Sunday afternoon. You can send me the credentials encrypted with GnuPG (key EE363E1F) via mail to marcus@fihlon.ch or using a secure messenger like Threema (my ID: M36HU8SN). If your prefer SMS I can send you my number via mail or PN.

**Comment by jangalinski** [comment]
I will get to you, but I myself won't be able to do this before sunday, so dont expect anything before later evening.
