### ISSUE TITLE
Compatibility with JUnit 5

### ISSUE THREAD

**Issue by YukiInu** [needle4j/needle4j#28]
Hi,

was trying to migrate our JUnit Framework to version 5 but the tests with NeedleRules are the last ones I don't get migrated due to the "@Rule" Annotation no longer present in Junit 5. seems it was replaced with extension mechanism and @ExtendWith

Are there plans on supporting Junit5 or are I overlooking something?

Kind regards

**Comment by jangalinski** [comment]
Sorry, but the needle4j lib ha been inactive for quite some time now ... it was very useful when working with JEE but after switching to spring and the advanced spring test tooling, I did not have the need to use or maintain it.
If there is still a use case for it, feel free to provide a PR, but I wont have time to deal with it in the near future.

**Comment by YukiInu** [comment]
Thanks for the fast reply.
At the moment the Vintage Engine helps as a workaround to get it running.
I'm not sure if I find the time soon to look into it and provide a PR.

**Comment by mdahm** [comment]
This issue has been fixed in needle4k:

https://github.com/needle4k/needle4k
